esphome:
  name: growcube
  friendly_name: GrowCube
  on_boot:
    then:
      # read the RTC time once when the system boots
      - ds1307.read_time

esp8266:
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: ""

ota:
  - platform: esphome
    password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Growcube Fallback Hotspot"
    password: ""

captive_portal:

i2c:
  sda: GPIO14
  scl: GPIO12
  scan: True  # Automatically scan for devices on the I2C bus

time:
  - platform: ds1307
    # repeated synchronization is not necessary unless the external RTC
    # is much more accurate than the internal clock
    update_interval: false
    
  - platform: homeassistant
    # instead try to synchronize via network repeatedly ...
    on_time_sync:
      then:
        # ... and update the RTC when the synchronization was successful
        ds1307.write_time:

ads1115:
  - address: 0x48

pca9554:
  id: 'pca9554a_device'
  pin_count: 16 
  address: 0x20  # Default I2C address for PCF9555

sensor:
  - platform: wifi_signal #reports the WiFi signal strength/RSSI in dB
    name: "WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 60s
    device_class: 'signal_strength'
    unit_of_measurement: 'dBm'
    entity_category: 'diagnostic'

  # Reports the WiFi signal strength in %
  - platform: copy
    source_id: wifi_signal_db
    name: "WiFi Signal Percent"
    icon: "mdi:wifi"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "%"
    entity_category: 'diagnostic'

  - platform: ads1115
    multiplexer: 'A0_GND'
    gain: 6.144
    name: "Soil sensor - D" 
    unit_of_measurement: '%'
    filters:
    - calibrate_linear:
        - 2.17 -> 0.00      # Calibrate Min in dry soil
        - 4.96 -> 100.00     # Calibrate MAX in 100% wet soil 
    - lambda: |
        if (x < 0) return 0;
        else if (x > 100) return 100;
        else return (x);
    accuracy_decimals: 0    
    
  - platform: ads1115
    multiplexer: 'A1_GND'
    gain: 6.144
    name: "Soil sensor - B" 
    unit_of_measurement: '%'
    filters:
    - calibrate_linear:
        - 2.17 -> 0.00      # Calibrate Min in dry soil
        - 4.96 -> 100.00     # Calibrate MAX in 100% wet soil 
    - lambda: |
        if (x < 0) return 0;
        else if (x > 100) return 100;
        else return (x);
    accuracy_decimals: 0    
       
  - platform: ads1115
    multiplexer: 'A2_GND'
    gain: 6.144
    name: "Soil sensor - C" 
    unit_of_measurement: '%'
    filters:
    - calibrate_linear:
        - 2.17 -> 0.00      # Calibrate Min in dry soil
        - 4.96 -> 100.00     # Calibrate MAX in 100% wet soil 
    - lambda: |
        if (x < 0) return 0;
        else if (x > 100) return 100;
        else return (x);
    accuracy_decimals: 0    
       
  - platform: ads1115
    multiplexer: 'A3_GND'
    gain: 6.144
    name: "Soil sensor - A" 
    unit_of_measurement: '%'
    filters:
    - calibrate_linear:
        - 2.17 -> 0.00      # Calibrate Min in dry soil
        - 4.96 -> 100.00     # Calibrate MAX in 100% wet soil 
    - lambda: |
        if (x < 0) return 0;
        else if (x > 100) return 100;
        else return (x);
    accuracy_decimals: 0    
           
  - platform: ina219
    address: 0x40
    shunt_resistance: 0.1 ohm
    current:
      name: "INA219 Current"
    power:
      name: "INA219 Power"
    bus_voltage:
      name: "INA219 Bus Voltage"
    shunt_voltage:
      name: "INA219 Shunt Voltage"
    max_voltage: 32.0V
    max_current: 3.2A
    update_interval: 2s
    
  - platform: aht10
    variant: AHT20
    temperature:
      name: "GrowCube Temperature"
    humidity:
      name: "GrowCube Humidity"
    update_interval: 60s

binary_sensor:
  - platform: gpio
    name: "EEPROM Button" #routed to 'EEPROM' button accessible through poke hole near grille for AHT20
    id: 'eeprom_button'
    internal: true
    pin:
      pca9554: pca9554a_device
      number: 0
      mode:
        output: true
      inverted: false
      
  - platform: gpio
    name: "User Button" #routed to 'User' button near grille for AHT20
    id: 'user_button'
    pin:
      pca9554: pca9554a_device
      number: 8
      mode:
        input: true
      inverted: false

light:
  - platform: status_led
    name: "Status LED"
    id: 'red_led'
    internal: true
    pin:
      pca9554: pca9554a_device
      number: 2
      mode:
        output: true
      inverted: false

switch:
  - platform: gpio
    name: "Buzzer"
    id: 'buzzer'
    pin:
      pca9554: pca9554a_device
      number: 1
      mode:
        output: true
      inverted: false

  - platform: gpio
    name: "Blue LED"
    id: 'blue_led'
    internal: true
    pin:
          pca9554: pca9554a_device
          number: 3
          mode:
            output: true
          inverted: false

  - platform: gpio
    name: "PCF9555 Pin #4" #routed near unpopulated Q122 (transistor for unpopulated relay) on empty pad for a 4.7k pulldown resistor
    internal: true
    pin:
      pca9554: pca9554a_device
      number: 4
      mode:
        output: true
      inverted: false

  - platform: gpio
    name: "Pump"
    pin:
      pca9554: pca9554a_device
      number: 5
      mode:
        output: true
      inverted: false

  - platform: gpio
    name: "Solenoid A"
    pin:
      pca9554: pca9554a_device
      number: 6
      mode:
        output: true
      inverted: false

  - platform: gpio
    name: "Solenoid B"
    pin:
      pca9554: pca9554a_device
      number: 7
      mode:
        output: true
      inverted: false

  - platform: gpio
    name: "Solenoid C"
    pin:
      pca9554: pca9554a_device
      number: 9
      mode:
        output: true
      inverted: false

  - platform: gpio
    name: "Solenoid D"
    pin:
      pca9554: pca9554a_device
      number: 10
      mode:
        output: true
      inverted: false

  - platform: gpio
    name: "PCF9555 Pin #11" #not routed
    internal: true
    pin:
      pca9554: pca9554a_device
      number: 11
      mode:
        output: true
      inverted: false

  - platform: gpio
    name: "PCF9555 Pin #12" #not routed
    internal: true
    pin:
      pca9554: pca9554a_device
      number: 12
      mode:
        output: true
      inverted: false

  - platform: gpio
    name: "PCF9555 Pin #13" #not routed
    internal: true
    pin:
      pca9554: pca9554a_device
      number: 13
      mode:
        output: true
      inverted: false

  - platform: gpio
    name: "PCF9555 Pin #14" #not routed
    internal: true
    pin:
      pca9554: pca9554a_device
      number: 14
      mode:
        output: true
      inverted: false

  - platform: gpio
    name: "PCF9555 Pin #15" #not routed
    internal: true
    pin:
      pca9554: pca9554a_device
      number: 15
      mode:
        output: true
      inverted: false

interval:
  - interval: 0.5s
    then:
      if:
        condition:
          - wifi.connected:
        then:
          if:
            condition:
              - switch.is_off: blue_led
            then:
              - switch.turn_on: blue_led
        else:
          - switch.toggle: blue_led
